managed_users:
  - name: admin_heichinger
    groups: ["sudo"]
    pubkey_file: "files/ssh_keys/admin_heichinger.pub"

  - name: admin_waldbauer
    groups: ["sudo"]
    pubkey_file: "files/ssh_keys/admin_waldbauer.pub"

  - name: admin_fiegl
    groups: ["sudo"]
    pubkey_file: "files/ssh_keys/admin_fiegl.pub"

  - name: admin_tayeh
    groups: ["sudo"]
    pubkey_file: "files/ssh_keys/admin_tayeh.pub"
